#!/bin/sh
# 模拟 Android dumpsys
case "$1" in
  battery)
cat <<'EOF'
Current Battery Service state:
  AC powered: false
  USB powered: true
  status: 2
  health: 2
  level: 87
  voltage: 4231
  temperature: 312
  technology: Li-ion
EOF
;;
  window)
cat <<'EOF'
WINDOW MANAGER WINDOWS (dumpsys window windows)
  Display: mDisplayId=0
    mCurrentFocus=Window{2f1e0a3 u0 com.example.demo/com.example.demo.MainActivity}
    mFocusedApp=ActivityRecord{1a2b3c u0 com.example.demo/.MainActivity t123}
EOF
;;
  activity)
cat <<'EOF'
ACTIVITY MANAGER ACTIVITIES (dumpsys activity activities)
  mResumedActivity: ActivityRecord{1a2b3c u0 com.example.demo/.MainActivity t123}
EOF
;;
esac
exit 0
